### ISSUE TITLE
needs puns

### ISSUE THREAD

**Issue by Chris-Johnston** [UWB-ACM/flask-barebones#4]
https://github.com/UWB-ACM/flask-barebones/blob/1ebec58a87e7a63a32e886fc3dde23de3c1aa457/src/punlist.txt#L1

currently the pun list is empty. this is an urgent issue that needs to be fixed.

**Comment by Chris-Johnston** [comment]
@UWB-ACM/hackathon-content-team we need puns ASAP

**Comment by Chris-Johnston** [comment]
@UWB-ACM/hackathon-content-team bump

**Comment by etcadinfinitum** [comment]
gonna work on this today @Chris-Johnston
